### PR TITLE
Moving readme to top level directory for clarity

### PR DESCRIPTION
**Pull request by asettle**
Moving the README up one level so other people know it exists. The management of publishing the upstream guides is within the remit of the docs team and we need to know where the instructions are. See: https://github.com/SUSE-Cloud/doc-cloud/pull/1111/

### CODE REVIEW

**Comment by asettle** [comment]
@dirkmueller could I please have write access to this repo?

**Comment by GarySmith** [comment]
LGTM

**Review by evrardjp — APPROVED** [review]

**Review by jeremy-moffitt — APPROVED** [review]
LGTM!

**Comment by dirkmueller** [comment]
@asettle the repo follows the normal rules, e.g. requiring reviews on pull requests.. you should be able to merge then if you're in the suse cloud maintainers group. feel free to ping me if things are urgent, I don't always read github notifications.

**Pull request merged**
